### ISSUE TITLE
wdio.conf.js need to be transpiled for wdio-html-reporter?

### ISSUE THREAD

**Issue by bedoro** [webdriverio-community/wdio-html-reporter#11]
Hello,
I would like to use the HTML report and have added the reporter library as it is descibed in the docs:

```
import { ReportAggregator, HtmlReporter} from '@rpii/wdio-html-reporter' ;
```

When I run `wdio wdioconf.js` now, I get this error:
```
wdio wdio.conf.js

2019-08-26T15:00:29.378Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: wdio.conf.js: Unexpected token {
wdio.conf.js:3
import { ReportAggregator, HtmlReporter} from '@rpii/wdio-html-reporter' ;
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

I understand what the error is telling me. But since the html-reporter is the only reason I need to transpile the config file, I'd like to hear the "best" way to do this from the authors of this plugin. 

Surely, you guys should have had the same problem. :)

**Comment by rpii** [comment]
the plugin is transpiledand release with transpiled code..  if you use the
legacy javascript syntax it will work fine.  I dont have a sample of it at
this location, but you could dig it out of some of the user comments in
github.

**Comment by msyrus** [comment]
An alternative import syntax could be
```
const { ReportAggregator, HtmlReporter } = require('@rpii/wdio-html-reporter') ;
```

**Comment by rpii** [comment]
thanks
