### ISSUE TITLE
Cannot set property 'failures' of undefined at HtmlReporter

### ISSUE THREAD

**Issue by mannysah** [webdriverio-community/wdio-html-reporter#46]
I get an error when i use HtmlReporter in my webdriverio config. 

Here are the versions:

"@rpii/wdio-html-reporter": "^6.3.1",
"@wdio/appium-service": "^6.11.0",
"webdriverio": "^6.12.0",
"@wdio/cli": "^6.12.0",
"@wdio/jasmine-framework": "^6.11.0",
"@wdio/local-runner": "^6.12.0",
"@wdio/spec-reporter": "^6.11.0",
"@wdio/sync": "^6.11.0",

Error is: 

`
[0-0] 2021-01-14T15:19:18.248Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot set property 'failures' of undefined
    at HtmlReporter.<anonymous> (<WORKSPACE>/node_modules/@wdio/reporter/build/index.js:153:32)
    at HtmlReporter.emit (events.js:315:20)
`

This error doesnt cause the execution to fail, however when there are other errors in codebase it doesn't show that error and outputs this error which makes debugging the actual issue very difficult.

**Comment by mannysah** [comment]
This error is caused by @wdio/runner. Closing it here.
