### ISSUE TITLE
 Couldn't initialise "wdio-html-nice-reporter". Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by randquraan** [webdriverio-community/wdio-html-reporter#99]
I'm facing this issue for a week, I tried all the solutions but I keep getting that:

2023-06-09T07:57:14.388Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialise "wdio-html-nice-reporter".
Error [ERR_REQUIRE_ESM]: require() of ES Module/node_modules/@wdio/reporter/build/index.js from /node_modules/wdio-html-nice-reporter/lib/htmlReporter.js not supported.
Instead change the require of index.js in /node_modules/wdio-html-nice-reporter/lib/htmlReporter.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (node_modules/wdio-html-nice-reporter/lib/htmlReporter.js:6:36)
    at require.extensions.<computed> [as .js] (/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/node_modules/wdio-html-nice-reporter/lib/index.js:7:40)
    at require.extensions.<computed> [as .js] (/node_modules/ts-node/dist/index.js:851:20)
    at safeRequire (//node_modules/@wdio/utils/build/utils.js:189:16)
    at initialisePlugin (/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at BaseReporter.initReporter (/node_modules/@wdio/runner/build/reporter.js:154:58)
    at Array.map (<anonymous>)
    at new BaseReporter (//node_modules/@wdio/runner/build/reporter.js:22:50)
    at Runner.run (/node_modules/@wdio/runner/build/index.js:78:26)
    at safeRequire (/node_modules/@wdio/utils/build/utils.js:192:15)
    at initialisePlugin (/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at BaseReporter.initReporter (/node_modules/@wdio/runner/build/reporter.js:154:58)
    at Array.map (<anonymous>)
    at new BaseReporter (/node_modules/@wdio/runner/build/reporter.js:22:50)
    at Runner.run( /node_modules/@wdio/runner/build/index.js:78:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by rpii** [comment]
You need to read up on the webdriver io changes to ESM.  There are some
changes you need to make.  you can look at the test code in the reporter to
see it.

**Comment by vdrulerz** [comment]
@rpii can you please help in sharing the direct file reference or the required changes in the configuration file, many people are struggling to get this reporter working with WDIO V8 so please help in sharing the same.

**Comment by samuelseverino** [comment]
I facing same issue! any solution?

**Comment by rpii** [comment]
Webdriver IO v 8 is an esm module.  you must use the v8 reporter and
convert your test to a module.  I have attached a tsconfig file that I have
used for my test.
